apiVersion: v1
kind: Service
metadata:
  name: sre-demo
  namespace: sre-portfolio
  labels:
    app: sre-demo
spec:
  selector:
    app: sre-demo
  ports:
    - name: http
      port: 80
      targetPort: 8080

